// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Music_Shop.Migrations
{
    [DbContext(typeof(MusicShopDbContext))]
    partial class MusicShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Data.Models.ExtraProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExtraProducts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Extra strings"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pack of mediators (5 pieces)"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Pack of mediators (15 pieces)"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Extra strings + pack of mediators (5 pieces)"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Extra strings + pack of mediators (15 pieces)"
                        },
                        new
                        {
                            Id = 6,
                            Name = "2 packs of extra strings"
                        },
                        new
                        {
                            Id = 7,
                            Name = "5 packs of extra strings"
                        },
                        new
                        {
                            Id = 8,
                            Name = "2 packs of extra strings + pack of mediators (5 pieces)"
                        },
                        new
                        {
                            Id = 9,
                            Name = "2 packs of extra strings + pack of mediators (15 pieces)"
                        },
                        new
                        {
                            Id = 10,
                            Name = "5 packs of extra strings + pack of mediators (5 pieces)"
                        },
                        new
                        {
                            Id = 11,
                            Name = "5 packs of extra strings + pack of mediators (15 pieces)"
                        });
                });

            modelBuilder.Entity("Music_Shop.Models.Guitar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExtraProductId")
                        .HasColumnType("int");

                    b.Property<int>("ExtraProductsId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.HasIndex("ExtraProductId");

                    b.ToTable("Guitars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "White",
                            ExtraProductsId = 11,
                            ImagePath = "https://www.muztorg.ru/files/1dd/71t/qsp/928/gsw/4cw/soo/88c/c/1dd71tqsp928gsw4cwsoo88cc.jpg",
                            Name = "Yamaha F310",
                            Price = 340f,
                            Type = "Western"
                        },
                        new
                        {
                            Id = 2,
                            Color = "Black",
                            ExtraProductsId = 6,
                            ImagePath = "https://www.muztorg.ru/files/1le/qe7/pgx/f6s/0s0/w40/og4/84s/w/1leqe7pgxf6s0s0w40og484sw.jpg",
                            Name = "Rockdale Aurora D1",
                            Price = 130f,
                            Type = "Dreadnought"
                        },
                        new
                        {
                            Id = 3,
                            Color = "Brown",
                            ExtraProductsId = 8,
                            ImagePath = "https://www.muztorg.ru/files/1rt/y8s/dbm/vhc/ks4/swg/4s4/o88/8/1rty8sdbmvhcks4swg4s4o888.jpeg",
                            Name = "Crafter D-7",
                            Price = 600f,
                            Type = "Dreadnought"
                        },
                        new
                        {
                            Id = 4,
                            Color = "Natural",
                            ExtraProductsId = 2,
                            ImagePath = "https://www.muztorg.ru/files/2rp/kok/xui/58g/gcw/04k/484/cg0/k/2rpkokxui58ggcw04k484cg0k.jpg",
                            Name = "Fender CD",
                            Price = 790f,
                            Type = "Dreadnought"
                        });
                });

            modelBuilder.Entity("Music_Shop.Models.Guitar", b =>
                {
                    b.HasOne("Data.Models.ExtraProduct", "ExtraProduct")
                        .WithMany("Guitars")
                        .HasForeignKey("ExtraProductId");

                    b.Navigation("ExtraProduct");
                });

            modelBuilder.Entity("Data.Models.ExtraProduct", b =>
                {
                    b.Navigation("Guitars");
                });
#pragma warning restore 612, 618
        }
    }
}
